## 4.3 Librería NumPy

El lenguaje de programación Python no fue diseñado originalmente para computación numérica, pero desde el principio atrajo la atención de la comunidad Científica y de Ingeniería.

Originalmente, cuando se querían trabajar con conjuntos de datos, se tenía que hacer con las estructuras "tradicionales"; que, como ya vimos, no siempre son lo más práctico. Son muy buenas para almacenar y crear datos, pero un poco estorbosas para realizar cálculos matemáticos.

Por ejemplo, ¿recuerdas qué pasaba cuando querías hacer operaciones matemáticas con listas?

In [1]:
lista = [1, 3, 5, 10] 
lista + 2

TypeError: can only concatenate list (not "int") to list

¡No se puede directamente! Para hacer una operación a _todos_ los elementos de una lista, necesitas hacerlo elemento por elemento...

In [2]:
lista2 = []
for i in range(len(lista)):
    lista2.append(lista[i] + 2)
    
lista2

[3, 5, 7, 12]

Son necesarias algunas líneas extras. Podría parecer que no es tan grande el problema...pero ahora imagínate qué va a pasar cuando queramos trabajar con más de una dimensión...

![image](https://live.staticflickr.com/65535/48367418307_77241f0b45_b.jpg)

Supongamos que quiero sumar un valor a _todos_ los elementos de la matriz. Para empezar, ¿cómo guardo esos elementos en Python?

Antes...hubiera sido con una lista _de listas_.

In [11]:
matriz = [[7, 18, 3], 
          [-6, 0, 12]]

matriz

[[7, 18, 3], [-6, 0, 12]]

In [16]:
## Y para sumar algún valor....
matriz2=[[],[]]
for i in range(len(matriz)):
    for j in range(len(matriz[i])):
        matriz2[i].append(matriz[i][j] + 2)

matriz2

[[9, 20, 5], [-4, 2, 14]]

Pff, qué complejo. Por fortuna, desde hace algunos años alguien ya creo el paquete NumPy, que nos ayuda a hacer esas operaciones mucho, mucho más fácil.

Para empezar, siempre que queramos usarlo, tenemos que importarlo. Nota que usamos el alias _np_, que es ya un estándar.

In [17]:
import numpy as np

También vamos a conocer una nueva estructura de datos: los arreglos de NumPy. ¿Qué eso? La respuesta corta sería: un arreglo NumPy es una lista en esteroides.

In [20]:
## Convertir de listas a arreglos NumPy es fácil:
arreglo=np.array(lista)
arreglo

array([ 1,  3,  5, 10])

Ve qué pasa cuando queremos sumar elementos a todos los elementos del arreglo...

In [21]:
arreglo + 2

array([ 3,  5,  7, 12])

...o multiplicar...

In [23]:
arreglo * 3

array([ 3,  9, 15, 30])

...o cualquier operación matemática, en realidad.

In [25]:
np.sqrt(arreglo)

array([1.        , 1.73205081, 2.23606798, 3.16227766])

Nota como, si queremos hacer operaciones, existen funciones específicas dentro del paquete NumPy. También podríamos hacerlo elemento por elemento, como antes...pero **siempre** serán más tardadas; no sólo por el tiempo perdido en escribir el código (más largo), sino también por la forma en la que la computadora hace los cálculos.

¿Y qué pasa cuando hay más de una dimensión?

In [28]:
arreglo2 = np.array(matriz)
arreglo2

array([[ 7, 18,  3],
       [-6,  0, 12]])

In [31]:
np.sin(arreglo2)

array([[ 0.6569866 , -0.75098725,  0.14112001],
       [ 0.2794155 ,  0.        , -0.53657292]])

¡NumPy no tiene problema para crear arreglos multidimensionales! Es más, vamos a conocer unos los métodos más útiles que tienen los arreglos

In [32]:
arreglo2.shape

(2, 3)

A partir de ahora, será bastante común estar confirmando las dimensiones de nuestros arreglos. Y, como puedes notarlo, el formato es **(filas, columnas)**. Es decir:
* Eje 0: Cuento hacia abajo.
* Eje 1: Cuento hacia la derecha.

De hecho, es muy parecido a como se marcan las dimensiones en álgebra matricial. Por cierto, hablando de eso...

** **Spoiler Alert** **

¿Conoces las matrices identidad?

In [35]:
identidad = np.identity(3)
identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

¿O recuerdas cómo hacer multiplicación de matrices?

In [44]:
np.matmul(arreglo2, identidad)

array([[ 7., 18.,  3.],
       [-6.,  0., 12.]])

¿O qué signficia transponer matrices?

In [45]:
arreglo2.T

array([[ 7, -6],
       [18,  0],
       [ 3, 12]])

Si no te suena, no te preocupes...seguramente verás esos temas en las siguientes semanas en tu clase de Álgebra Matricial.
Porque sí; NumPy va de la mano con el Álgebra de Matrices. Y no es casualidad, ya que es la mejor forma de realizar cálculos con grandes dimensiones de datos.

## Extracción (filtrado) de datos en Arreglos.

Volvamos a ocupar nuestros arreglos. Primero, cuando tenemos 1 dimensión:

In [47]:
arreglo

array([ 1,  3,  5, 10])

¡Extraer es igual que como lo haríamos con una lista!

In [49]:
arreglo[0]

1

In [52]:
arreglo[2]

5

¿Y con dos (o más) dimensiones?

In [55]:
arreglo2

array([[ 7, 18,  3],
       [-6,  0, 12]])

In [59]:
# Podemos hacerlo igual que cuando teníamos listas de listas
arreglo2[0][1]

18

In [58]:
# O ahora podemos hacerlo dentro de un mismo corchete...
arreglo2[0, 1]

18

Sólo recuerda el orden: primer se especifica la hilera (hacia abajo) y luego la columna (hacia la derecha).

## Operaciones por ejes

¿Qué pasa con las operaciones como la **suma**? A veces querremos sumar todos los elementos del arreglo entre sí...pero otra veces vamos a querer sumar sólo los elementos que están en la misma fila, o por columna. Para eso, podemos encontrar el argumento opcional `axis`.

* Si uso axis=0, sumo hacia abajo.
* Si uso axis=1, sumo hacia la derecha.

In [78]:
arreglo2

array([[ 7, 18,  3],
       [-6,  0, 12]])

In [81]:
np.sum(arreglo2, axis=0)

array([ 1, 18, 15])

In [82]:
np.sum(arreglo2, axis=1)

array([28,  6])

In [84]:
# También se puede usar como método
arreglo2.sum(axis=1)

array([28,  6])

In [85]:
# Y si no especifico eje, se suman TODOS los elementos.
np.sum(arreglo2)

34

In [90]:
# Y hay varias operaciones parecidas...
arreglo2.prod(axis=0)

array([-42,   0,  36])

### Arrays con otros tipos de datos 
Por cierto, también pueden haber arreglos con datos que sean *string*.

De hecho, a diferencia de las estructuras de datos básicas en Python, los arreglos de NumPy sólo pueden contener datos de un sólo tipo.

Si introduces datos de tipos distintos en un mismo arreglo, NumPy va a cambiarlos en automático.

In [91]:
# Cuando trabajo con listas, Python respeta el tipo de dato
datos = [[1, 2, 3], 
         [4, 5, "seis"]]

datos

[[1, 2, 3], [4, 5, 'seis']]

In [95]:
# Pero cuando los convierto a arreglos de NumPy, todos se vuelven texto, y les aparecen "comillas".
arreglo3 = np.array(datos)
arreglo3

array([['1', '2', '3'],
       ['4', '5', 'seis']], dtype='<U11')

Incluso puedes ver algo que dice _dtype_; se refiere al tipo de datos contenidos (que son un poco diferente a los de Python "tradicional").

Otra forma rápida de consultarlo es usando directamente el método.

In [93]:
arreglo2.dtype

dtype('int32')

In [97]:
arreglo3.dtype

dtype('<U11')